version: "3.8"

services:
  credit_card_management_db:
    image: postgres:14
    container_name: credit_card_management_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
  credit_card_management_backend:
    build: 
      context: .
      dockerfile: Dockerfile_Backend
    environment:
      - DB=host=credit_card_management_db user=postgres password=postgres dbname=postgres port=5432 sslmode=disable TimeZone=Asia/Shanghai
    depends_on:
      - credit_card_management_db
    ports:
      - '8888:8888'
    volumes:
      - './:/app'
   