version: "3.8"

services:
  meiwa_1880:
    build: ./node-red-1880
    container_name: meiwa_1880
    ports:
      - '1880:1880'
    volumes:
      - ./node-red-1880:/app
      - /app/node_modules
  meiwa_1881:
    build: ./node-red-1881
    container_name: meiwa_1881
    ports:
      - '1881:1880'
      - '1433:1433'
      - '27017:27017'
    volumes:
      - ./node-red-1881:/app
      - /app/node_modules
  meiwa_1894:
    build: ./1894
    container_name: meiwa_1894
    ports:
      - '1894:1880'
    volumes:
      - ./1894:/app
      - /app/node_modules
